### ISSUE TITLE
PersonPrepareForSim runs into trouble when creating large number (millions) of vehicles

### ISSUE THREAD

**Issue by balacmi** [matsim-org/matsim-libs#1424]
Currently we require that every person needs to be assigned a vehicle for each main and network mode, which is fine. This is currently done here:

https://github.com/matsim-org/matsim-libs/blob/20c5f447e8ed3e8ca998631a45c72efdfd991769/matsim/src/main/java/org/matsim/core/controler/PrepareForSimImpl.java#L164

Now going a step forward when the vehicle is created it is added to the VehiclesImpl object here:
https://github.com/matsim-org/matsim-libs/blob/20c5f447e8ed3e8ca998631a45c72efdfd991769/matsim/src/main/java/org/matsim/vehicles/VehiclesImpl.java#L75

Currently [VehiclesImpl](https://github.com/matsim-org/matsim-libs/blob/20c5f447e8ed3e8ca998631a45c72efdfd991769/matsim/src/main/java/org/matsim/vehicles/VehiclesImpl.java
) uses IdMap-s to store information about all vehicles. Without going into the implementation of the IdMap and its performance benefit in this context, we have found out that in cases when we want to simulate large-scale scenarios (read, more than 4mil vehicles needs to be created) the construction time of these IdMap-s becomes too long (read, can take days). 

My suggestion would be to either roll back to LinkedHashMap which was used previously, or to use a LinkedHashMap in cases when we have let's say more than 5mil vehicles and otherwise to use an IdMap. This works well in or set-ups and even for 20million vehicles, it takes some seconds to construct the needed objects. As I said I did not look into the IdMap itself to see if something can be improved there.

**Comment by sebhoerl** [comment]
Probably a solution might be to pass an initial size to the IdMap when it is created in `VehiclesImpl` through some config value.

**Comment by ikaddoura** [comment]
Thanks Milos, just a few days ago I stumbled upon the same issue. In several of our models we have several network modes (e.g. 3-5 different freight types) which makes the simulation take forever even for "small" sample sizes...

**Comment by michalmac** [comment]
@balacmi Some ideas for improving the map expansion that you may try out:
 - `IdMap.INCREMENT_FACTOR` from 1.5 to 2.0: https://github.com/matsim-org/matsim-libs/blob/master/matsim/src/main/java/org/matsim/api/core/v01/IdMap.java#L19
 - expanding the array wrt index in: https://github.com/matsim-org/matsim-libs/blob/master/matsim/src/main/java/org/matsim/api/core/v01/IdMap.java#L156, i.e. replacing
   ```java
   Math.max(index + INCREMENT, (int)(data.length * INCREMENT_FACTOR))
   ```
   with
   ```java
   Math.max(index + INCREMENT, (int)(index * INCREMENT_FACTOR))
   ```

**Comment by mrieser** [comment]
> we have found out that in cases when we want to simulate large-scale scenarios (read, more than 4mil vehicles needs to be created) the construction time of these IdMap-s becomes too long (read, can take days).

Interesting. Can you reproduce this? I would love to figure out, why it is like this. If I do a simple test like this:

```java
Object o = new Object();
IdMap<Vehicle, Object> map = new IdMap<>(Vehicle.class);
String[] modes = new String[] { "car", "bike", "drt", "walk", "ride"};

for (String mode : modes) {
    for (int i = 0; i < 4_000_000; i++) {
        Id<Vehicle> vehId = Id.create(mode + "_" + i, Vehicle.class);
        map.put(vehId, o);
    }
}
```

This passes in a few seconds (about 7 seconds on my machine), generating 20 million Ids and storing it.

As this is very far away from "days", I suspect there is some very special combination that triggers the issue which I would love to have a closer look to.

**Comment by balacmi** [comment]
Hey Marcel, Just a quick thought, this might have to do with the fact that these IDs are here sorted already. When those are read from the population map they are not. This might be the reason why you cannot replicate it here?

**Comment by mrieser** [comment]
Test-Code for random Ids: I create Ids with random values, then sort them, then insert them into the Map. This way, the insertion order does not correlate to the order of Id creation

```java
Object o = new Object();
List<Id<Vehicle>> ids = new ArrayList<>();
HashMap<Id<Vehicle>, Object> map = new HashMap<>();
String[] modes = new String[] { "car", "bike", "drt", "walk", "ride"};
LOG.info("creating ids");

Random r = new Random(123456L);
for (String mode : modes) {
    for (int i = 0; i < 4_000_000; i++) {
        Id<Vehicle> vehId = Id.create(r.nextInt(90_000_000) + "_" + mode, Vehicle.class);
        ids.add(vehId);
    }
}
LOG.info("sort Ids");
ids.sort(Id::compareTo);
LOG.info("start");
long start = System.currentTimeMillis();
for (Id<Vehicle> id : ids) {
    map.put(id, o);
}
long end = System.currentTimeMillis();
LOG.info("final size " + map.size());
LOG.info("duration: " + (end - start) / 1000.0);
```

The creation now takes longer due to the PRNG being used and the sorting, but the insertion into the Map again only takes a few seconds.

**Comment by balacmi** [comment]
Hi Marcel,

So I found the right way to reproduce the issue in a meaningful way:

```java
Config config = ConfigUtils.createConfig();
Scenario scenario = ScenarioUtils.createMutableScenario(config);

for (int i = 0; i < 8_000_000; i++) {
   scenario.getPopulation()
      .addPerson(scenario.getPopulation().getFactory().createPerson(Id.createPersonId(i)));
}

Map<Id<Vehicle>, Vehicle> map = new IdMap<>(Vehicle.class);
String[] modes = new String[] { "car", "bike", "drt", "walk" };
VehicleType type = new VehicleType(Id.create("something", VehicleType.class));
int i = 0;
long start = System.currentTimeMillis();

for (Person person : scenario.getPopulation().getPersons().values()) {
   for (String mode : modes) {
      Id<Vehicle> vehId = Id.create(person.getId() + "_" + mode, Vehicle.class);
      Vehicle v = new VehicleImpl(vehId, type);
      map.put(vehId, v);
      if (i % 10_0000 == 0)
	  LOG.info(i + " time: " + (System.currentTimeMillis() - start)/1000.0);
      i++;
   }
}
long end = System.currentTimeMillis();
```

This is what will take considerable time to compute (currently running with 100GB of memory). This replicates the adding of vehicles from the population that I have, which initially (before adding it to the scenario) has all persons sorted by id. If we instead use a LinkedHashMap the whole thing is done in 46.4s using 50GB memory.

**Comment by mrieser** [comment]
Hi Milos,

The above code runs on my laptop with 8GB, reporting 37.6 seconds at the end.

BUT: I had to slightly modify the code, as `new VehicleType(..)` and `new VehicleImpl(..)` are no longer public. Instead, I had to use the factory (`scenario.getVehicles().getFactory().createVehicleType(..)`, ...).

What version of MATSim are you using? In the original version of `IdMap`, the resizing was not optimal (slow and requiring lot of new memory). But this was fixed [in June 2020](https://github.com/matsim-org/matsim-libs/commit/04280d898751d68208c788eb456212d6d6b05061#diff-8a3d694d3930fe13331fa6101ea34986aae6692b22104b7f182c997e4b35f5ee). It would thus be helpful to know which version of MATSim you are using, and if you have tested your code with a rather recent version of MATSim or not.

**Comment by balacmi** [comment]
I see it now. We are using the last release, so v12.0, and this change went in some 2 weeks after the v12.0 was released... Then no issue with current development version ;). I am sorry for not noticing this earlier. 

Anyway it helps to know that in v12.0 this is still an issue for anybody who might require large scale simulations. As we require stable release to work on, I guess a temporary solution will be needed until the next release.

**Comment by Janekdererste** [comment]
The next release will be in April.
